name: multilingual_voice_app
description: A new Flutter project for multilingual voice calls.

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.12.3
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.0
  permission_handler: ^11.3.1
  http: ^1.2.2 # Updated to a compatible version
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
